GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKb2huIiwiZW1haWwiOiJtYWlsQGVtYWlsLmNvbSIsImlhdCI6MTY1MjMyOTI2MiwiZXhwIjoxNjUyMzI5MjgyfQ.STpTjCWLHTh0qFw2Ntqn8_3pBsX7kWykfx79MEhBgnQ
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"Khalid",
    "email":"mails2@email.com",
    "password":"123452",
    "confPassword":"222"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"mail@email.com",
    "password":"123456"
}

###
GET  http://localhost:5000/token

###
DELETE  http://localhost:5000/logout
